// SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
// SPDX-License-Identifier: BSD-3-Clause-Open-MPI
// Portions of this file may implement 3GPP specifications, which may be subject to additional licensing requirements.

/*******************************************************************************
 *
 *                     3GPP TS ASN1 NRPPA v18.7.0 (2025-12)
 *
 ******************************************************************************/

#pragma once

#include "ocudu/asn1/asn1_ap_utils.h"

namespace asn1 {
namespace nrppa {

/*******************************************************************************
 *                             Constant Definitions
 ******************************************************************************/

#define ASN1_NRPPA_MAX_PRIVATE_IES 65535
#define ASN1_NRPPA_MAX_PROTOCOL_EXTS 65535
#define ASN1_NRPPA_MAX_PROTOCOL_IES 65535
#define ASN1_NRPPA_ID_ERROR_IND 0
#define ASN1_NRPPA_ID_PRIVATE_MSG 1
#define ASN1_NRPPA_ID_E_C_ID_MEAS_INITIATION 2
#define ASN1_NRPPA_ID_E_C_ID_MEAS_FAIL_IND 3
#define ASN1_NRPPA_ID_E_C_ID_MEAS_REPORT 4
#define ASN1_NRPPA_ID_E_C_ID_MEAS_TERMINATION 5
#define ASN1_NRPPA_ID_O_TDOA_INFO_EXCHANGE 6
#define ASN1_NRPPA_ID_ASSIST_INFO_CTRL 7
#define ASN1_NRPPA_ID_ASSIST_INFO_FEEDBACK 8
#define ASN1_NRPPA_ID_POSITIONING_INFO_EXCHANGE 9
#define ASN1_NRPPA_ID_POSITIONING_INFO_UPD 10
#define ASN1_NRPPA_ID_MEAS 11
#define ASN1_NRPPA_ID_MEAS_REPORT 12
#define ASN1_NRPPA_ID_MEAS_UPD 13
#define ASN1_NRPPA_ID_MEAS_ABORT 14
#define ASN1_NRPPA_ID_MEAS_FAIL_IND 15
#define ASN1_NRPPA_ID_T_RP_INFO_EXCHANGE 16
#define ASN1_NRPPA_ID_POSITIONING_ACTIVATION 17
#define ASN1_NRPPA_ID_POSITIONING_DEACTIVATION 18
#define ASN1_NRPPA_ID_P_RS_CFG_EXCHANGE 19
#define ASN1_NRPPA_ID_MEAS_PRECFG 20
#define ASN1_NRPPA_ID_MEAS_ACTIVATION 21
#define ASN1_NRPPA_ID_S_R_SI_NFORMATION_RESERV_NOTIF 22
#define ASN1_NRPPA_MAX_NR_OF_ERRORS 256
#define ASN1_NRPPA_MAX_CELLIN_RA_NNODE 3840
#define ASN1_NRPPA_MAX_IDXES_REPORT 64
#define ASN1_NRPPA_MAX_NO_MEAS 64
#define ASN1_NRPPA_MAX_CELL_REPORT 9
#define ASN1_NRPPA_MAX_CELL_REPORT_NR 9
#define ASN1_NRPPA_MAXNO_OTDO_ATYPES 63
#define ASN1_NRPPA_MAX_SERV_CELL 5
#define ASN1_NRPPA_MAX_EUTRA_MEAS 8
#define ASN1_NRPPA_MAX_GERAN_MEAS 8
#define ASN1_NRPPA_MAX_NR_MEAS 8
#define ASN1_NRPPA_MAX_UTRAN_MEAS 8
#define ASN1_NRPPA_MAX_WLA_NCHS 16
#define ASN1_NRPPA_MAXNO_FREQ_HOP_BANDS_MINUS_ONE 7
#define ASN1_NRPPA_MAX_NO_PATH 2
#define ASN1_NRPPA_MAX_NR_OF_POS_SI_MSG 32
#define ASN1_NRPPA_MAXNO_ASSIST_INFO_FAIL_LIST_ITEMS 32
#define ASN1_NRPPA_MAX_NR_OF_SEGMENTS 64
#define ASN1_NRPPA_MAX_NR_OF_POS_SIBS 32
#define ASN1_NRPPA_MAX_NO_OF_MEAS_TR_PS 64
#define ASN1_NRPPA_MAXNO_TR_PS 65535
#define ASN1_NRPPA_MAXNO_TRP_INFO_TYPES 64
#define ASN1_NRPPA_MAXNOOF_ANGLE_INFO 65535
#define ASN1_NRPPA_MAXNOLCS_GCS_TRANSLATION 3
#define ASN1_NRPPA_MAXNO_BCAST_CELL 16384
#define ASN1_NRPPA_MAXNO_SRS_TRIGGER_STATES 3
#define ASN1_NRPPA_MAXNO_SPATIAL_RELATIONS 64
#define ASN1_NRPPA_MAXNO_POS_MEAS 16384
#define ASN1_NRPPA_MAXNO_SRS_CARRIERS 32
#define ASN1_NRPPA_MAXNO_SC_SS 5
#define ASN1_NRPPA_MAXNO_SRS_RES_FEATURES 64
#define ASN1_NRPPA_MAXNO_SRS_POS_RES 64
#define ASN1_NRPPA_MAXNO_SRS_RES_SETS 16
#define ASN1_NRPPA_MAXNO_SRS_RES_PER_SET 16
#define ASN1_NRPPA_MAXNO_SRS_POS_RES_SETS 16
#define ASN1_NRPPA_MAXNO_SRS_POS_RES_PER_SET 16
#define ASN1_NRPPA_MAX_PRS_RES_SETS 2
#define ASN1_NRPPA_MAX_PRS_RES_PER_SET 64
#define ASN1_NRPPA_MAX_NO_SS_BS 255
#define ASN1_NRPPA_MAXNOOF_PR_SRES_SET 8
#define ASN1_NRPPA_MAXNOOF_PR_SRES 64
#define ASN1_NRPPA_MAXNOOF_UL_AO_AS 8
#define ASN1_NRPPA_MAX_NO_PATH_EXTENDED 8
#define ASN1_NRPPA_MAXNO_AR_PS 16
#define ASN1_NRPPA_MAXNO_UE_TE_GS 256
#define ASN1_NRPPA_MAXNO_TRPTE_GS 8
#define ASN1_NRPPA_MAX_FREQ_LAYERS 4
#define ASN1_NRPPA_MAX_NUM_RES_PER_ANGLE 24
#define ASN1_NRPPA_MAXNO_AZIMUTH_ANGLES 3600
#define ASN1_NRPPA_MAXNO_ELEVATION_ANGLES 1801
#define ASN1_NRPPA_MAXNO_PRSTR_PS 256
#define ASN1_NRPPA_MAXNO_VA_CELL 32
#define ASN1_NRPPA_MAXNOAGGR_POS_SRS_RES_FEATURES 3
#define ASN1_NRPPA_MAXNOAGGR_POS_SRS_RES_SETS 3
#define ASN1_NRPPA_MAXNO_AGG_POS_PRS_RES_SETS 3
#define ASN1_NRPPA_MAXNOOF_TIME_WIN_SRS 16
#define ASN1_NRPPA_MAXNOOF_TIME_WIN_MEAS 16
#define ASN1_NRPPA_MAXNO_PRECFG_SRS 16
#define ASN1_NRPPA_MAXNOOF_HOPS_MINUS_ONE 5
#define ASN1_NRPPA_MAXNO_AGG_COMBINATIONS 2
#define ASN1_NRPPA_MAXNO_AGGR_POS_SRS_COMBINATIONS 32
#define ASN1_NRPPA_ID_CAUSE 0
#define ASN1_NRPPA_ID_CRIT_DIAGNOSTICS 1
#define ASN1_NRPPA_ID_LMF_UE_MEAS_ID 2
#define ASN1_NRPPA_ID_REPORT_CHARACTERISTICS 3
#define ASN1_NRPPA_ID_MEAS_PERIODICITY 4
#define ASN1_NRPPA_ID_MEAS_QUANTITIES 5
#define ASN1_NRPPA_ID_RAN_UE_MEAS_ID 6
#define ASN1_NRPPA_ID_E_C_ID_MEAS_RESULT 7
#define ASN1_NRPPA_ID_OTDOA_CELLS 8
#define ASN1_NRPPA_ID_OTDOA_INFO_TYPE_GROUP 9
#define ASN1_NRPPA_ID_OTDOA_INFO_TYPE_ITEM 10
#define ASN1_NRPPA_ID_MEAS_QUANTITIES_ITEM 11
#define ASN1_NRPPA_ID_REQUESTED_SRS_TX_CHARACTERISTICS 12
#define ASN1_NRPPA_ID_CELL_PORTION_ID 14
#define ASN1_NRPPA_ID_OTHER_RAT_MEAS_QUANTITIES 15
#define ASN1_NRPPA_ID_OTHER_RAT_MEAS_QUANTITIES_ITEM 16
#define ASN1_NRPPA_ID_OTHER_RAT_MEAS_RESULT 17
#define ASN1_NRPPA_ID_WLAN_MEAS_QUANTITIES 19
#define ASN1_NRPPA_ID_WLAN_MEAS_QUANTITIES_ITEM 20
#define ASN1_NRPPA_ID_WLAN_MEAS_RESULT 21
#define ASN1_NRPPA_ID_TDD_CFG_EUTRA_ITEM 22
#define ASN1_NRPPA_ID_ASSIST_INFO 23
#define ASN1_NRPPA_ID_BROADCAST 24
#define ASN1_NRPPA_ID_ASSIST_INFO_FAIL_LIST 25
#define ASN1_NRPPA_ID_SRS_CFG 26
#define ASN1_NRPPA_ID_MEAS_RESULT 27
#define ASN1_NRPPA_ID_TRP_ID 28
#define ASN1_NRPPA_ID_TRP_INFO_TYPE_LIST_TRP_REQ 29
#define ASN1_NRPPA_ID_TRP_INFO_LIST_TRP_RESP 30
#define ASN1_NRPPA_ID_MEAS_BEAM_INFO_REQUEST 31
#define ASN1_NRPPA_ID_RESULT_SS_RSRP 32
#define ASN1_NRPPA_ID_RESULT_SS_RSRQ 33
#define ASN1_NRPPA_ID_RESULT_CSI_RSRP 34
#define ASN1_NRPPA_ID_RESULT_CSI_RSRQ 35
#define ASN1_NRPPA_ID_ANGLE_OF_ARRIVAL_NR 36
#define ASN1_NRPPA_ID_GEOGRAPHICAL_COORDINATES 37
#define ASN1_NRPPA_ID_POSITIONING_BROADCAST_CELLS 38
#define ASN1_NRPPA_ID_LMF_MEAS_ID 39
#define ASN1_NRPPA_ID_RAN_MEAS_ID 40
#define ASN1_NRPPA_ID_TRP_MEAS_REQUEST_LIST 41
#define ASN1_NRPPA_ID_TRP_MEAS_RESP_LIST 42
#define ASN1_NRPPA_ID_TRP_MEAS_REPORT_LIST 43
#define ASN1_NRPPA_ID_SRS_TYPE 44
#define ASN1_NRPPA_ID_ACTIVATION_TIME 45
#define ASN1_NRPPA_ID_SRS_RES_SET_ID 46
#define ASN1_NRPPA_ID_TRP_LIST 47
#define ASN1_NRPPA_ID_SRS_SPATIAL_RELATION 48
#define ASN1_NRPPA_ID_SYS_FRAME_NUM 49
#define ASN1_NRPPA_ID_SLOT_NUM 50
#define ASN1_NRPPA_ID_SRS_RES_TRIGGER 51
#define ASN1_NRPPA_ID_TRP_MEAS_QUANTITIES 52
#define ASN1_NRPPA_ID_ABORT_TX 53
#define ASN1_NRPPA_ID_SFN_INITISATION_TIME 54
#define ASN1_NRPPA_ID_RESULT_NR 55
#define ASN1_NRPPA_ID_RESULT_EUTRA 56
#define ASN1_NRPPA_ID_TRP_INFO_TYPE_ITEM 57
#define ASN1_NRPPA_ID_CGI_NR 58
#define ASN1_NRPPA_ID_SFN_INITISATION_TIME_NR 59
#define ASN1_NRPPA_ID_CELL_ID 60
#define ASN1_NRPPA_ID_SRS_FREQ 61
#define ASN1_NRPPA_ID_TRP_TYPE 62
#define ASN1_NRPPA_ID_SRS_SPATIAL_RELATION_PER_SRS_RES 63
#define ASN1_NRPPA_ID_MEAS_PERIODICITY_EXTENDED 64
#define ASN1_NRPPA_ID_PRS_RES_ID 65
#define ASN1_NRPPA_ID_PRSTRP_LIST 66
#define ASN1_NRPPA_ID_PRS_TX_TRP_LIST 67
#define ASN1_NRPPA_ID_ON_DEMAND_PRS 68
#define ASN1_NRPPA_ID_AO_A_SEARCH_WIN 69
#define ASN1_NRPPA_ID_TRP_MEAS_UPD_LIST 70
#define ASN1_NRPPA_ID_ZO_A 71
#define ASN1_NRPPA_ID_RESP_TIME 72
#define ASN1_NRPPA_ID_UE_REPORT_INFO 73
#define ASN1_NRPPA_ID_MULTIPLE_UL_AO_A 74
#define ASN1_NRPPA_ID_UL_SRS_RSRP_P 75
#define ASN1_NRPPA_ID_SRS_RESTYPE 76
#define ASN1_NRPPA_ID_EXTENDED_ADD_PATH_LIST 77
#define ASN1_NRPPA_ID_ARP_LOCATION_INFO 78
#define ASN1_NRPPA_ID_ARP_ID 79
#define ASN1_NRPPA_ID_LO_S_N_LO_SI_NFORMATION 80
#define ASN1_NRPPA_ID_UE_TX_TEG_ASSOC_LIST 81
#define ASN1_NRPPA_ID_NOF_TRP_RX_TEG 82
#define ASN1_NRPPA_ID_NOF_TRP_RX_TX_TEG 83
#define ASN1_NRPPA_ID_TRP_TX_TEG_ASSOC 84
#define ASN1_NRPPA_ID_TRPTEG_INFO 85
#define ASN1_NRPPA_ID_TRP_RX_TEG_INFO 86
#define ASN1_NRPPA_ID_TRP_PRS_INFO_LIST 87
#define ASN1_NRPPA_ID_PRS_MEASS_INFO_LIST 88
#define ASN1_NRPPA_ID_PRS_CFG_REQUEST_TYPE 89
#define ASN1_NRPPA_ID_UE_TEG_INFO_REQUEST 90
#define ASN1_NRPPA_ID_MEAS_TIME_OCCASION 91
#define ASN1_NRPPA_ID_MEAS_CHARACTERISTICS_REQUEST_IND 92
#define ASN1_NRPPA_ID_TRP_BEAM_ANT_INFO 93
#define ASN1_NRPPA_ID_NR_TADV 94
#define ASN1_NRPPA_ID_MEAS_AMOUNT 95
#define ASN1_NRPPA_ID_PATH_PWR 96
#define ASN1_NRPPA_ID_PRECFG_RESULT 97
#define ASN1_NRPPA_ID_REQUEST_TYPE 98
#define ASN1_NRPPA_ID_UE_TEG_REPORT_PERIODICITY 99
#define ASN1_NRPPA_ID_SRS_PORT_IDX 100
#define ASN1_NRPPA_ID_PROC_CODE_101_NOT_TO_BE_USED 101
#define ASN1_NRPPA_ID_PROC_CODE_102_NOT_TO_BE_USED 102
#define ASN1_NRPPA_ID_PROC_CODE_103_NOT_TO_BE_USED 103
#define ASN1_NRPPA_ID_UE_TX_TIMING_ERROR_MARGIN 104
#define ASN1_NRPPA_ID_MEAS_PERIODICITY_NR_AO_A 105
#define ASN1_NRPPA_ID_SRS_TX_STATUS 106
#define ASN1_NRPPA_ID_NROF_SYMBOLS_EXTENDED 107
#define ASN1_NRPPA_ID_REPEAT_FACTOR_EXTENDED 108
#define ASN1_NRPPA_ID_START_RB_HOP 109
#define ASN1_NRPPA_ID_START_RB_IDX 110
#define ASN1_NRPPA_ID_TX_COMBN8 111
#define ASN1_NRPPA_ID_EXTENDED_RES_SYMBOL_OFFSET 112
#define ASN1_NRPPA_ID_NEW_NR_CGI 113
#define ASN1_NRPPA_ID_MOBILE_TRP_LOCATION_INFO 114
#define ASN1_NRPPA_ID_MOBILE_IAB_MT_UE_ID 115
#define ASN1_NRPPA_ID_MOBILE_ACCESS_POINT_LOCATION 116
#define ASN1_NRPPA_ID_COMMON_TA_PARAMS 117
#define ASN1_NRPPA_ID_UE_RX_TX_TIME_DIFF 118
#define ASN1_NRPPA_ID_SCS_480 119
#define ASN1_NRPPA_ID_SCS_960 120
#define ASN1_NRPPA_ID_BW_AGGREGATION_REQUEST_IND 121
#define ASN1_NRPPA_ID_POS_SRS_RES_SET_AGGREGATION_LIST 122
#define ASN1_NRPPA_ID_TIMING_REPORT_GRANULARITY_FACTOR_EXTENDED 123
#define ASN1_NRPPA_ID_TIME_WIN_INFO_SRS_LIST 124
#define ASN1_NRPPA_ID_TIME_WIN_INFO_MEAS_LIST 125
#define ASN1_NRPPA_ID_UL_RS_CP_MEAS 126
#define ASN1_NRPPA_ID_SYMBOL_IDX 127
#define ASN1_NRPPA_ID_POS_VALIDITY_AREA_CELL_LIST 128
#define ASN1_NRPPA_ID_SRS_RESERV_TYPE 129
#define ASN1_NRPPA_ID_PRSBW_AGGREGATION_REQUEST_INFO_LIST 130
#define ASN1_NRPPA_ID_AGGR_POS_SRS_RES_ID_LIST 131
#define ASN1_NRPPA_ID_AGGR_PRS_RES_SET_LIST 132
#define ASN1_NRPPA_ID_TRP_PHASE_QUALITY 133
#define ASN1_NRPPA_ID_NEW_CELL_ID 134
#define ASN1_NRPPA_ID_VALIDITY_AREA_SPECIFIC_SRS_INFO 135
#define ASN1_NRPPA_ID_REQUESTED_SRS_PRECFG_CHARACTERISTICS_LIST 136
#define ASN1_NRPPA_ID_SRS_PRECFG_LIST 137
#define ASN1_NRPPA_ID_SRS_INFO 138
#define ASN1_NRPPA_ID_TX_HOP_CFG 139
#define ASN1_NRPPA_ID_MEASURED_FREQ_HOPS 140
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS1 141
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS2 142
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS3 143
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS4 144
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS5 145
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS6 146
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS1_ADD_PATH 147
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS2_ADD_PATH 148
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS3_ADD_PATH 149
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS4_ADD_PATH 150
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS5_ADD_PATH 151
#define ASN1_NRPPA_ID_REPORT_GRANULARITYKMINUS6_ADD_PATH 152
#define ASN1_NRPPA_ID_MEASURED_RESULTS_ASSOCIATED_INFO_LIST 153
#define ASN1_NRPPA_ID_POINT_A 154
#define ASN1_NRPPA_ID_NR_PCI 155
#define ASN1_NRPPA_ID_SCS_SPECIFIC_CARRIER 156
#define ASN1_NRPPA_ID_MEAS_BASED_ON_AGGR_RES 157
#define ASN1_NRPPA_ID_UE_REPORT_INTERV_MILLISECONDS 158
#define ASN1_NRPPA_ID_REMOTE_UE_IND_REQUEST 159
#define ASN1_NRPPA_ID_REMOTE_UE_IND 160
#define ASN1_NRPPA_ID_REMOTE_UE_STATUS 161
#define ASN1_NRPPA_ID_LOCAL_ORIGIN 162
#define ASN1_NRPPA_ID_PRECFG_SRS_INFO 163
#define ASN1_NRPPA_ID_DL_REF_SIG_UE_RX_TX_TD 164
#define ASN1_NRPPA_ID_SRS_POS_PERIODIC_CFG_HYPER_SFN_IDX 165
#define ASN1_NRPPA_ID_VALIDITY_AREA_SPECIFIC_SRS_INFO_EXTENDED 166

/*******************************************************************************
 *                              Struct Definitions
 ******************************************************************************/

// PrivateIE-ID ::= CHOICE
struct private_ie_id_c {
  struct types_opts {
    enum options { local, global, nulltype } value;

    const char* to_string() const;
  };
  using types = enumerated<types_opts>;

  // choice methods
  private_ie_id_c() = default;
  void          set(types::options e = types::nulltype);
  types         type() const { return type_; }
  OCUDUASN_CODE pack(bit_ref& bref) const;
  OCUDUASN_CODE unpack(cbit_ref& bref);
  void          to_json(json_writer& j) const;
  // getters
  uint32_t& local()
  {
    assert_choice_type(types::local, type_, "PrivateIE-ID");
    return c;
  }
  const uint32_t& local() const
  {
    assert_choice_type(types::local, type_, "PrivateIE-ID");
    return c;
  }
  uint32_t& set_local();
  void      set_global();

private:
  types    type_;
  uint32_t c;
};

// PrivateIE-Field{NRPPA-PRIVATE-IES : IEsSetParam} ::= SEQUENCE{{NRPPA-PRIVATE-IES}}
template <class ies_set_paramT_>
struct private_ie_field_s {
  private_ie_id_c                   id;
  crit_e                            crit;
  typename ies_set_paramT_::value_c value;

  OCUDUASN_CODE pack(bit_ref& bref) const;
  OCUDUASN_CODE unpack(cbit_ref& bref);
  void          to_json(json_writer& j) const;
};

// PrivateIE-Container{NRPPA-PRIVATE-IES : IEsSetParam} ::= SEQUENCE (SIZE (1..65535)) OF
// PrivateIE-Field{NRPPA-PRIVATE-IES : IEsSetParam}
template <class ies_set_paramT_>
using private_ie_container_l = dyn_seq_of<private_ie_field_s<ies_set_paramT_>, 1, 65535, true>;

template <class valueT_>
struct private_ie_container_item_s {
  private_ie_id_c id;
  crit_e          crit;
  valueT_         value;

  // sequence methods
  private_ie_container_item_s(private_ie_id_c id_, crit_e crit_);
  OCUDUASN_CODE pack(bit_ref& bref) const;
  OCUDUASN_CODE unpack(cbit_ref& bref);
  void          to_json(json_writer& j) const;
};

} // namespace nrppa
} // namespace asn1
