# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI


set(OCUDU_VERSION_MAJOR 26)
set(OCUDU_VERSION_MINOR 04)
set(OCUDU_VERSION_PATCH 0)
set(OCUDU_VERSION_STRING "${OCUDU_VERSION_MAJOR}.${OCUDU_VERSION_MINOR}.${OCUDU_VERSION_PATCH}")