// SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
// SPDX-License-Identifier: BSD-3-Clause-Open-MPI

#include "ocudu/ocudulog/ocudulog.h"
#include "fmt/format.h"
#include "fmt/std.h"
#include <gtest/gtest.h>
#include <optional>

class format_optional_test : public ::testing::Test
{
protected:
  void SetUp() override
  {
    // init test's logger
    ocudulog::init();
    logger.set_level(ocudulog::basic_levels::debug);
  }

  void TearDown() override
  {
    // flush logger after each test
    ocudulog::flush();
  }

  ocudulog::basic_logger& logger = ocudulog::fetch_basic_logger("TEST", false);
};

TEST_F(format_optional_test, opt_uint32_t)
{
  uint32_t                value           = 4711;
  std::optional<uint32_t> opt_val_present = value;
  std::optional<uint32_t> opt_val_empty   = {};
  logger.debug("Test: value={} opt_value_present={} opt_value_empty={}", value, opt_val_present, opt_val_empty);
  EXPECT_EQ(fmt::format("{}", opt_val_present), "4711");
  EXPECT_EQ(fmt::format("{}", opt_val_empty), "{na}");
  // The following unwanted outputs are generated by the unpatched default formatter of the fmt library
  EXPECT_NE(fmt::format("{}", opt_val_present), "optional(4711)") << "Found unwanted format; unpatched formatter";
  EXPECT_NE(fmt::format("{}", opt_val_empty), "none") << "Found unwanted format; unpatched formatter";
}

TEST_F(format_optional_test, opt_double)
{
  double                value           = 12.345;
  std::optional<double> opt_val_present = value;
  std::optional<double> opt_val_empty   = {};
  logger.debug("Test: value={} opt_value_present={} opt_value_empty={}", value, opt_val_present, opt_val_empty);
  EXPECT_EQ(fmt::format("{}", opt_val_present), "12.345");
  EXPECT_EQ(fmt::format("{}", opt_val_empty), "{na}");
  // The following unwanted outputs are generated by the unpatched default formatter of the fmt library
  EXPECT_NE(fmt::format("{}", opt_val_present), "optional(12.345)") << "Found unwanted format; unpatched formatter";
  EXPECT_NE(fmt::format("{}", opt_val_empty), "none") << "Found unwanted format; unpatched formatter";
}

TEST_F(format_optional_test, opt_double_fmt_spec)
{
  double                value           = 12.345;
  std::optional<double> opt_val_present = value;
  std::optional<double> opt_val_empty   = {};
#define OPT_DOUBLE_FMT_SPEC ":.1f"
  logger.debug("Test: value={" OPT_DOUBLE_FMT_SPEC "} opt_value_present={" OPT_DOUBLE_FMT_SPEC
               "} opt_value_empty={" OPT_DOUBLE_FMT_SPEC "}",
               value,
               opt_val_present,
               opt_val_empty);
  EXPECT_EQ(fmt::format("{" OPT_DOUBLE_FMT_SPEC "}", opt_val_present), "12.3");
  EXPECT_EQ(fmt::format("{" OPT_DOUBLE_FMT_SPEC "}", opt_val_empty), "{na}");
  // The following unwanted outputs are generated by the unpatched default formatter of the fmt library
  EXPECT_NE(fmt::format("{" OPT_DOUBLE_FMT_SPEC "}", opt_val_present), "optional(12.3)")
      << "Found unwanted format; unpatched formatter";
  EXPECT_NE(fmt::format("{" OPT_DOUBLE_FMT_SPEC "}", opt_val_empty), "none")
      << "Found unwanted format; unpatched formatter";
}

int main(int argc, char** argv)
{
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
