# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI


[[outputs.file]]
  files       = ["${TELEGRAF_DUMP_FILE:-stdout}"]
  namedrop    = ["internal_*"] # Ignore internal metrics
  data_format = "influx"
