version = 1

[[annotations]]
path = [
    "CLI11.hpp",
]
SPDX-FileCopyrightText = "2017-2026 University of Cincinnati, developed by Henry Schreiner under NSF AWARD 1414736. All rights reserved."
SPDX-License-Identifier = "BSD-3-Clause"
